# Generated by Django 4.2 on 2023-04-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default='place_name', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='phone',
            field=models.IntegerField(default='09123456789'),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='place',
            field=models.ForeignKey(default='9999', on_delete=django.db.models.deletion.CASCADE, to='MVP.destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='address',
            field=models.TextField(default='plcae_add', max_length=500),
        ),
    ]
