# Generated by Django 4.2 on 2023-04-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0003_alter_entertainment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
